# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        return np.full(shape, value)
    elif mode == 'identity':
        return np.eye(shape)
    else:
        raise ValueError(f"Unknown mode: {mode}")

# Test cases
print("Zeros array (3x3):")
print(array_factory('zeros', (3, 3)))
print("\nOnes array (2x4):")
print(array_factory('ones', (2, 4)))
print("\nFull array with value 5 (2x3):")
print(array_factory('full', (2, 3), 5))
print("\nIdentity matrix (4x4):")
print(array_factory('identity', 4))

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

# Test case
branch_a = [1, 2, 3, 4, 5, 6] 
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

result = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print("Combined dataset:")
print(result)
print(f"\nResulting shape: {result.shape}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [ ]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)
    
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

# Test cases
print("Test 1 - Basic threshold application:")
v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)
print(f"Input: {v}")
print(f"Threshold: 2, Replacement: -20")
print(f"Output: {result}\n")

print("Test 2 - Sales data threshold:")
sales = [150, 200, 155, 300, 210, 180]
result2 = apply_threshold(sales, 200, -1)
print(f"Input: {sales}")
print(f"Threshold: 200, Replacement: -1")
print(f"Output: {result2}")

TestCase

In [ ]:
# Complete workflow: Reshape and Stack
print("=" * 60)
print("COMPLETE WORKFLOW: Reshape and Stack")
print("=" * 60)

# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print("\nBranch A (reshaped from 1D to 2x3):")
print(np.array(branch_a).reshape(2, 3))
print("\nBranch B (already 2x3):")
print(np.array(branch_b))
print("\nFinal Report (Stacked):")
print(final_report)
print(f"\nResulting shape: {final_report.shape}  # (4, 3) - 4 rows, 3 columns")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Final Test: apply_threshold
print("\n" + "=" * 60)
print("FINAL TEST: apply_threshold")
print("=" * 60)

v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)

print(f"\nInput array: {v}")
print(f"Threshold: 2")
print(f"Replacement value: -20")
print(f"\nOutput: {result}")
print(f"\nExplanation:")
print(f"  - Element 1: 1 < 2 (not >= 2) → stays 1")
print(f"  - Element 2: 2 >= 2 (True) → replaced with -20")
print(f"  - Element 3: 3 >= 2 (True) → replaced with -20")

array([  1, -20, -20])

In [ ]:
# Summary of all NumPy solutions
print("\n" + "=" * 60)
print("NUMPY ASSIGNMENT SUMMARY")
print("=" * 60)

print("\n✓ Part 1: array_factory()")
print("-" * 60)
print("Modes supported:")
print("  • 'zeros' → np.zeros(shape)")
print("  • 'ones' → np.ones(shape)")
print("  • 'full' → np.full(shape, value)")
print("  • 'identity' → np.eye(shape)")

print("\n✓ Part 2: secure_reshape_and_stack()")
print("-" * 60)
print("Process:")
print("  1. Convert inputs to NumPy arrays")
print("  2. Reshape first array to new dimensions")
print("  3. Vertically stack both arrays (vstack)")
print("  4. Handle errors with try-except")

print("\n✓ Part 3: apply_threshold()")
print("-" * 60)
print("Process:")
print("  1. Convert input to NumPy array")
print("  2. Create boolean condition (arr >= threshold)")
print("  3. Use np.where() to replace elements")
print("  4. Return modified array")

print("\n" + "=" * 60)
print("All assignments completed successfully!")
print("=" * 60)