In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 3.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.3 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.3 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.3 MB 2.9 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/12.3 MB 3.0 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.3 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.3 MB 3.1 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.3 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.3 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.8/12.3 MB 3.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.1/12.3 MB 3.1 MB/s eta 0:00:02
   ----------

In [6]:
import numpy as np 
v1 = np.array([10,6,20])
v2 = np.array([1,5,22])

print(v1 - v2)
print(v1 * 5)
print(v1.dot(v2))

[ 9  1 -2]
[ 50  30 100]
480


In [8]:
m1= np.array([
    [1,2,3],
    [4,5,6],
    [8,9,10]
])
print(m1)
print("===========================")
m2 = m1= np.array([
    [11,12,13],
    [14,15,16],
    [18,19,200]
])

print(m2.dot(m1))

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
[[  523   559  2935]
 [  652   697  3622]
 [ 4064  4301 40538]]


In [10]:
s = np.array(5)
print(s.ndim)
print(s.shape)

0
()


In [15]:
v1 = np.array([[1,2,3],
              
              [4,5,6],
              [5,6,8]])
print(v1.ndim)
print(v1.shape)

2
(3, 3)


In [ ]:
vec_1 =np.array([1,2,3,4,5,6])
mat_1 = vec_1.reshape((3,2))
print(mat_1)






[[1 2]
 [3 4]
 [5 6]]


In [ ]:

import numpy as np 
def reshape_col_vec(mat):
    mat_1 = vec_1.reshape((x,y))
    return mat_1

vec_2 =np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
print(mat_2)


[[1]
 [2]
 [3]
 [4]]


In [26]:
mat_3 = m1= np.array([
    [1,2,3],
    [4,5,6],
    [8,9,10.2]
])
print(mat_3.dtype)
print(mat_3)

float64
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 8.   9.  10.2]]


In [24]:
mat_4 = m1= np.array([
    [1,2,3],
    [4,5,6]
    
])
print(mat_3.dtype)
print(mat_3)

float64
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 8.   9.  10.2]]


In [34]:
class C:
    c = 3

o1 = C()


mat_6 = m1= np.array([
    [1,2,3],
    [4,5,6],
    [9,10.2]
])
print(mat_6.dtype)
print(mat_6)


f_mat = mat_6.astype(float)

print(f_mat)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
array([])

TypeError: float() argument must be a string or a real number, not 'C'